name: Code checks
on:
  - push
  - pull_request
jobs:
  typecheck_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly-2021-07-23
      - run: rustup default nightly-2021-07-23
      - run: rustup component add rustfmt clippy
      - run: cargo check
      - run: cargo test
      - run: cargo clippy
